[package]

name = "intervallum"
version = "0.6.3"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

description = "Generic interval and interval set library."
documentation = "http://hyc.io/intervallum"
repository = "https://github.com/ptal/intervallum"
readme = "README.md"
keywords = ["interval", "math", "data-structure", "containers", "interval-set"]
license = "MIT/Apache-2.0"

[lib]

name = "interval"
path = "src/libinterval/lib.rs"

[dependencies]

num = "^0.1.29"
bit-set = "^0.2.0"
gcollections = "^0.3.0"
