[package]

name = "intervallum"
version = "0.4.5"
authors = [ "Pierre Talbot <ptalbot@hyc.io>" ]

description = "Generic interval and interval set library."
documentation = "http://hyc.io/intervallum"
repository = "https://github.com/ptal/rust-interval"
readme = "README.md"
keywords = ["interval", "math", "data-structure", "containers", "interval-set"]
license = "Apache-2.0"

[lib]

name = "interval"
path = "src/libinterval/lib.rs"

[dependencies]

num = "^0.1.24"
